### PR TITLE
Add support for remote Hyper-V; Fix style

### PR DESCRIPTION
**Pull request by thheinen**
# Description

Allow use of remote Hyper-V servers for Test Kitchen machines.

Based on Train (3.5+) abilities to upload files and the Train WinRM backend for remote execution, still allowing all existing PS commands to be used.

## Issues Resolved

Feature Request #10 

Also adjusted style to recent recommendations and fixed tests.

## Check List

- [X] All tests pass. See TESTING.md for details.
- [X] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by thheinen** [comment]
@tas50 Got a minute to check this or can you ping someone? The project has no reviewers set. Thanks :)

**Comment by tas50** [comment]
@tecracer-theinen I'm not the best person at this point, but I'll make sure we get this reviewed

**Comment by thheinen** [comment]
If this is a problem with people being available, I can offer to maintain this driver until someone else steps in.

**Comment by tecracer-theinen** [comment]
If persons being available is the limiting factor, I can offer to maintain/extend this driver until someone else steps in.

**Review by xorima — APPROVED** [review]
Seems sensible enough

**Pull request merged**
